apiVersion: apps/v1
kind: Deployment
metadata:
  name: ali-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ali-app
  template:
    metadata:
      labels:
        app: ali-app
    spec:
      containers:
      - name: ali-app
        image: mohammadalihaider96/ali-app:v1
        ports:
        - containerPort: 5000